# Generated by Django 4.1.1 on 2024-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_movie_description_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title_orig']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='title_orig',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies_of_genre', to='viewer.genre'),
        ),
    ]
