# Generated by Django 4.1.1 on 2024-05-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_country_movie_length_movie_title_cz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
