# Generated by Django 4.1.1 on 2024-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_people_movie_actors_movie_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
