# Generated by Django 4.1.1 on 2024-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_people_biography_alter_people_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='surname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
